[project]
name = "mechadealer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ntplib>=0.4.0",
    "python-dotenv>=1.1.0",
    "questdb[dataframe]>=2.0.3",
    "ruff>=0.11.2",
]
