[project]
# Project dependencies are defined in the individual workspace members (in libs/ and projects/).
# `uv` will collect and resolve them from there.
dependencies = []
description = "Add your description here"
name = "mechadealer"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[tool.uv.workspace]
members = [
  "projects/*",
  "libs/*",
]

[tool.uv.sources]
brokerlib = { workspace = true }
coreutils = { workspace = true }
datastore = { workspace = true }
kafkalib = { workspace = true }
storelib = { workspace = true }
strategylib = { workspace = true }

[dependency-groups]
dev = [
    "pyright>=1.1.398",
    "ruff>=0.11.2",
    "typing>=3.10.0.0",
    "poethepoet>=0.27.0",
]

[tool.poe.tasks]
datasync = "uv run --package datasync -- python projects/datasync/main.py"
app-server = "uv run --package app-server -- uvicorn projects.app_server.main:app --reload --port 8000"

[tool.pyright]
reportMissingTypeArgument = true
strictListInference = true

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []
