services:
  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    ports:
      - "9000:9000" # Web Console (UI), REST API
      - "9009:9009" # InfluxDB Line Protocol (ILP)
      - "8812:8812" # PGWire
      - "9003:9003" # Min Health Server
    volumes:
      - type: bind
        source: ${PWD}/.questdb
        target: /var/lib/questdb

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100" # Loki REST API
    volumes:
      - ./loki_data:/var/lib/loki/data
      - ./loki_config:/etc/loki
    command: "-config.file=/etc/loki/loki-config.yaml"

  kafka:
    image: apache/kafka:4.0.0
    hostname: broker
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092,CONTROLLER://broker:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    restart: always
    ports:
      - "9001:9000"
    environment:
      KAFKA_BROKERCONNECT: broker:29092
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      - kafka

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1235789
      POSTGRES_DB: pgdb
    volumes:
      - pg_data:/var/lib/postgresql/data

  datasync:
    build:
      context: ..
      dockerfile: projects/datasync/Dockerfile
    container_name: datasync
    restart: always
    depends_on:
      - questdb
      - kafka
    env_file:
      - ../.env
    environment:
      - KAFKA_BROKER_ADDRESS=kafka:29092
      - QDB_CONNECTION_STRING=${QDB_CONNECTION_STRING_COMPOSE}
      - QDB_CLIENT_CONF=${QDB_CLIENT_CONF_COMPOSE}

volumes:
  pg_data: